// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIxSi90gs_b4fsbOfK5HJAWowtBqjRymU',
    appId: '1:194728074873:web:2f20a800b806cc77d6fea8',
    messagingSenderId: '194728074873',
    projectId: 'chatapp-926d2',
    authDomain: 'chatapp-926d2.firebaseapp.com',
    storageBucket: 'chatapp-926d2.firebasestorage.app',
    measurementId: 'G-BLS40NEYZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKkShmOXCkEj-f_nFUjNqbOzDof6PZdn0',
    appId: '1:194728074873:android:50af6f58f8f0da06d6fea8',
    messagingSenderId: '194728074873',
    projectId: 'chatapp-926d2',
    storageBucket: 'chatapp-926d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUXGpGhBlHFlR9MsyVA5iF-yJ-oghH62g',
    appId: '1:194728074873:ios:368cb24fbb3c5f9dd6fea8',
    messagingSenderId: '194728074873',
    projectId: 'chatapp-926d2',
    storageBucket: 'chatapp-926d2.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUXGpGhBlHFlR9MsyVA5iF-yJ-oghH62g',
    appId: '1:194728074873:ios:368cb24fbb3c5f9dd6fea8',
    messagingSenderId: '194728074873',
    projectId: 'chatapp-926d2',
    storageBucket: 'chatapp-926d2.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIxSi90gs_b4fsbOfK5HJAWowtBqjRymU',
    appId: '1:194728074873:web:fae9f0168fe35a67d6fea8',
    messagingSenderId: '194728074873',
    projectId: 'chatapp-926d2',
    authDomain: 'chatapp-926d2.firebaseapp.com',
    storageBucket: 'chatapp-926d2.firebasestorage.app',
    measurementId: 'G-JXGXMVT5GC',
  );
}
